version: '3'
services:
  # serviceregistry:
  #   image: 'usernow/service-registry:0.0.1'
  #   container_name: serviceregistry
  #   ports:
  #     - '8761:8761'
  # configserver:
  #   image: 'usernow/config-server:0.0.1'
  #   container_name: configserver
  #   ports:
  #     - '9296:9296'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://configserver:9296/actuator/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   depends_on:
  #     - serviceregistry
  # cloudgateway:
  #   image: 'usernow/api-gateway:latest'
  #   container_name: cloudgateway
  #   ports:
  #     - '9090:9090'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #     - CONFIG_SERVER_URL=http://configserver:9296/
  #   depends_on:
  #     configserver:
  #       condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
