server:
  port: 8082


spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED



management:
  tracing:
    sampling:
      probability: 1.0

meli:
  client-id: ${MELI_CLIENT_ID:3755041179926330}
  client-secret: ${MELI_CLIENT_SECRET:ciwie6JXlq9iMidcOP8MHFwzqL2RsRgd}
  redirect-uri: ${MELI_REDIRECT_URI:https://www.testapp.com}
  code: ${MELI_AUTHORIZATION_CODE:TG-67f59da41190b90001756a69-32729035}
  code-verifier: ${MELI_CODE_VERIFIER:}
  access-token: ${ACCESS_TOKEN:APP_USR-3755041179926330-040915-5ece9b375c6ebd874999b97dd54fcc41-32729035}
  refresh-token: ${REFRESH_TOKEN:TG-67f6cb548905050001d12fda-32729035}
