apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-srv"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-cm
data:
  init.sql: |
    CREATE DATABASE couponDB;
