apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon
  template:
    metadata:
      labels:
        app: coupon
    spec:
      containers:
      - name: coupon
        image: usernow/coupon-service:latest
        ports:
        - containerPort: 8082
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url
          - name: KAFKA_BROKERS
            value: "kafka-srv"
        resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
        
---

apiVersion: v1
kind: Service
metadata:
  name: coupon-srv
spec:
  type: ClusterIP
  selector:
    app: coupon
  ports:
    - name: coupon
      protocol: TCP
      port: 80
      targetPort: 8082